# Generated by Django 5.1.1 on 2024-09-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title',
            field=models.CharField(default='Dice Time', max_length=100),
        ),
    ]
