# Generated by Django 5.1.1 on 2024-09-17 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_lrg_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoochProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('located', models.CharField(max_length=50)),
                ('pup_prof_img', models.ImageField(default='ppi/pupdefault.jpg', upload_to='ppi/')),
            ],
        ),
    ]
