# Generated by Django 5.1.1 on 2024-09-18 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_petprofile_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
        migrations.AddField(
            model_name='homepage',
            name='lrg_banner_2',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
