# Generated by Django 5.1.1 on 2024-09-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_header_homepage_lrg_banner_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lrg_banner_3',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
