# Generated by Django 5.1.1 on 2024-09-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_aboutpage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='body_text',
            new_name='body_text1',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body_text2',
            field=models.TextField(default='Hello'),
        ),
    ]
