# Generated by Django 5.1.1 on 2024-09-19 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_body_text_aboutpage_body_text1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body_text',
            new_name='body_text1',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_text2',
            field=models.TextField(default='Hello'),
        ),
    ]
