# Generated by Django 5.1.1 on 2024-09-19 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_body_text_homepage_body_text1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='petprofile',
            name='title',
            field=models.CharField(default='Sparky Needs A Title', max_length=50),
        ),
    ]
