# Generated by Django 5.1.1 on 2024-09-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_petprofile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_text2_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
