# Generated by Django 5.1.1 on 2024-09-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_privacypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_text', models.TextField()),
            ],
        ),
    ]
