# Generated by Django 5.1.1 on 2024-09-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_termspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body_text1_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
