# Generated by Django 5.1.1 on 2024-09-21 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_homepage_body_text1_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_text1_img',
            field=models.ImageField(default='banners/default.jpg', max_length=500, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_text2_img',
            field=models.ImageField(default='banners/default.jpg', max_length=500, upload_to='banners/'),
        ),
    ]
