# Generated by Django 5.1.1 on 2024-09-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_homepage_body_text1_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body_text1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_text1_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_text2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body_text2_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
